version = "1.0"

[main]
name = "Main configuration"
services = ["__APP__"]

    [main.auth]
    name = "Authentication"

        [main.auth.auth]
        ask = "Auth type"
        type = "select"
        choices = ["none", "password"]
        default = "none"
        optional = false
        bind = ":__INSTALL_DIR__/config.yaml"

        [main.auth.password]
        ask = "Password"
        type = "password"
        optional = true
        visible = "auth == 'password'"
    
    [main.extensions]
    name = "Extensions"
    optional = false

        [main.extensions.extensions_gallery_info]
        type = "alert"
        ask = "Read more about the Extention Gallery on [code-server FAQ](https://coder.com/docs/code-server/latest/FAQ#why-cant-code-server-use-microsofts-extension-marketplace)."
        style = "info"

        [main.extensions.extensions_gallery]
        ask = "Extensions Gallery"
        type = "string"
        example = "{\"serviceUrl\": \"https://open-vsx.org/vscode/gallery\",\"itemUrl\": \"https://open-vsx.org/vscode/item\"}"
        help = "[Documentation](https://coder.com/docs/code-server/latest/FAQ#how-do-i-use-my-own-extensions-marketplace)"
        optional = false
        bind = ":__INSTALL_DIR__/code-server.env"

        [main.extensions.enable_proposed_api]
        ask = "Enable Proposed API"
        type = "tags"
        optional = true
