packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.17.0~ynh2"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/coder/code-server/releases/download/v4.17.0/code-server-4.17.0-linux-amd64.tar.gz"
        amd64.sha256 = "12ba07cee7b6c5bbd172f8bac52bb01029f4d291cb22615d1ec92b9760d6546d"
        arm64.url = "https://github.com/coder/code-server/releases/download/v4.17.0/code-server-4.17.0-linux-arm64.tar.gz"
        arm64.sha256 = "4c71fc2660f4f3f580f8ba1a6858a8d5cf99e0805d27b5e7db79672c5777d967"
        armhf.url = "https://github.com/coder/code-server/releases/download/v4.17.0/code-server-4.17.0-linux-armv7l.tar.gz"
        armhf.sha256 = "0a8755393281ecb82ebbf6344b0e2ea3b6dee3024457d1d6a28489d8a8eeb3f6"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "code-server-.*-linux-arm64.tar.gz"
        autoupdate.asset.amd64 = "code-server-.*-linux-amd64.tar.gz"
        autoupdate.asset.armhf = "code-server-.*-linux-armv7l.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"
