packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.95.2~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/coder/code-server/releases/download/v4.95.2/code-server-4.95.2-linux-amd64.tar.gz"
        amd64.sha256 = "0fbe4fa4a59333deededa3e1eb5a4a3d23c6f083d1c749679ee44cdffbc8cda9"
        arm64.url = "https://github.com/coder/code-server/releases/download/v4.95.2/code-server-4.95.2-linux-arm64.tar.gz"
        arm64.sha256 = "61151ac6c06f16d8686b928f2b8302570e862232521388e539a50868f455045a"
        armhf.url = "https://github.com/coder/code-server/releases/download/v4.95.2/code-server-4.95.2-linux-armv7l.tar.gz"
        armhf.sha256 = "0bc67f9bd903432ea54078c6e4a24e825f8b64228bf7d958a184098b25edd289"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "code-server-.*-linux-arm64.tar.gz"
        autoupdate.asset.amd64 = "code-server-.*-linux-amd64.tar.gz"
        autoupdate.asset.armhf = "code-server-.*-linux-armv7l.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"
