packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.12.0~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 11.1.17"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/coder/code-server/releases/download/v4.13.0/code-server-4.13.0-linux-amd64.tar.gz"
        amd64.sha256 = "de103fb2d7f6df1395c6a6692c1dccb1474895cd2bc467be457e039ab9d858ac"
        arm64.url = "https://github.com/coder/code-server/releases/download/v4.13.0/code-server-4.13.0-linux-arm64.tar.gz"
        arm64.sha256 = "e9d81ae13a6f02c3350c0eca021d6b0b381bf459475fcbcc3e861fa3d19b1eff"
        armhf.url = "https://github.com/coder/code-server/releases/download/v4.13.0/code-server-4.13.0-linux-armv7l.tar.gz"
        armhf.sha256 = "20aed6fb13424edc2c1997e3241dc4c7d51a29e0a3e7349696715f61d10762c7"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "code-server-*-linux-arm64.tar.gz"
        autoupdate.asset.amd64 = "code-server-*-linux-amd64.tar.gz"
        autoupdate.asset.armhf = "code-server-*-linux-armv7l.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"
    mail.allowed = "__ADMIN__"
