packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.96.2~ynh2"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/coder/code-server/releases/download/v4.96.2/code-server-4.96.2-linux-amd64.tar.gz"
        amd64.sha256 = "e3f454f5b5cd9f4d064a2163548b0fdec076d18d87f99187c41a618b502c31a5"
        arm64.url = "https://github.com/coder/code-server/releases/download/v4.96.2/code-server-4.96.2-linux-arm64.tar.gz"
        arm64.sha256 = "3303e8e9ed088e95e7cf2af3f0dfcc6f472b90c4582bbc5a0a287b42c181ce33"
        armhf.url = "https://github.com/coder/code-server/releases/download/v4.96.2/code-server-4.96.2-linux-armv7l.tar.gz"
        armhf.sha256 = "c1fd455402d6bc6c43b01b7273d231c2e732968b1fd492e879530af4c039a2cf"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "code-server-.*-linux-arm64.tar.gz"
        autoupdate.asset.amd64 = "code-server-.*-linux-amd64.tar.gz"
        autoupdate.asset.armhf = "code-server-.*-linux-armv7l.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"
