packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.92.2~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/coder/code-server/releases/download/v4.92.2/code-server-4.92.2-linux-amd64.tar.gz"
        amd64.sha256 = "c385f50afd0346f727fe3af2a2baf94c3857338fe4cbf4cc9933aaa8c690e57b"
        arm64.url = "https://github.com/coder/code-server/releases/download/v4.92.2/code-server-4.92.2-linux-arm64.tar.gz"
        arm64.sha256 = "84efd84f1c4fefe9fb2b71018b68052b9f8265d5e1f515bf3d62f7fcfd896bbc"
        armhf.url = "https://github.com/coder/code-server/releases/download/v4.92.2/code-server-4.92.2-linux-armv7l.tar.gz"
        armhf.sha256 = "2dde08f4b0403833e9d3d60f005f1863efeaf764cdd4bd89e8b1d870664a8e2b"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "code-server-.*-linux-arm64.tar.gz"
        autoupdate.asset.amd64 = "code-server-.*-linux-amd64.tar.gz"
        autoupdate.asset.armhf = "code-server-.*-linux-armv7l.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"
