packaging_format = 2

id = "code-server"
name = "code-server"
description.en = "Run VS Code on your server and access it in the browser"
description.fr = "Lancez VS Code sur votre serveur et accédez-y depuis votre navigateur"

version = "4.16.1~ynh2"

maintainers = ["Tagada"]

[upstream]
license = "MIT"
website = "https://coder.com"
admindoc = "https://coder.com/docs/code-server/latest"
userdoc = "https://coder.com/docs/code-server/latest/FAQ"
code = "https://github.com/coder/code-server"

[integration]
yunohost = ">= 11.1.17"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/coder/code-server/releases/download/v4.16.1/code-server-4.16.1-linux-amd64.tar.gz"
        amd64.sha256 = "e10bc642be9fe8a802f556737b1bbb910ef818979a35034b092c85e62a42d1a7"
        arm64.url = "https://github.com/coder/code-server/releases/download/v4.16.1/code-server-4.16.1-linux-arm64.tar.gz"
        arm64.sha256 = "a256429887531d855baaa6b14b25906f69fa4b4a977b1ae0def001016fb37b81"
        armhf.url = "https://github.com/coder/code-server/releases/download/v4.16.1/code-server-4.16.1-linux-armv7l.tar.gz"
        armhf.sha256 = "38081417b8e10160f4c54aea93b24faeeb1bafbd4e41de021fd78a673f09daa6"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "code-server-.*-linux-arm64.tar.gz"
        autoupdate.asset.amd64 = "code-server-.*-linux-amd64.tar.gz"
        autoupdate.asset.armhf = "code-server-.*-linux-armv7l.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    subdirs = ["user-data", "extensions"]

    [resources.permissions]
    main.url = "/"
